#### Sr. Engineer: Dhruv Singh <br> Project Name: Success Classifier <br> Phase: Modelling - KNN Pt. 3 <br> Date Updated: 01/22/2022

In [1]:
#import all libraries

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn import preprocessing 
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
pwd()

'C:\\Dhruv\\Data\\4_Machine_Learning_with_Python\\3_Supervised Learning Essential Training\\Phase II - Modelling\\3_KNN_v1_01.22.2022'

In [3]:
# Load data
df = pd.read_csv('1_readonly/Services.csv')

# Proportion of response variable
df['Employed'].value_counts()

0    27513
1    10750
Name: Employed, dtype: int64

In [4]:
# Prepare Data
X = df.iloc[:, 0:-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [6]:
# Sets to experiment with
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size = 0.40)
scaler = StandardScaler()
scaler.fit(X_train2)
X_train2 = scaler.transform(X_train2)
X_test2 = scaler.transform(X_test2)


In [7]:
# Basic Knn
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train2, y_train2)

KNeighborsClassifier()

In [8]:
# Gridsearch
params = {"n_neighbors":[2,3,4,5,6,7,8,9]}
model = GridSearchCV(classifier, params, cv=3)

In [9]:
model.fit(X_train, y_train)
model.best_params_

{'n_neighbors': 8}

In [10]:
model.best_score_

0.7061900521457294

In [11]:
# Knn with 3 neighbors
gridsearch_knn = KNeighborsClassifier(n_neighbors = 8)
gridsearch_knn.fit(X_train2, y_train2)

KNeighborsClassifier(n_neighbors=8)

In [12]:
gridsearch_y_pred = gridsearch_knn.predict(X_test2)
print(gridsearch_y_pred)

[0 0 0 ... 0 0 0]


In [13]:
print(confusion_matrix(y_test2, gridsearch_y_pred))
print(classification_report(y_test2, gridsearch_y_pred))

[[10389   627]
 [ 3772   518]]
              precision    recall  f1-score   support

           0       0.73      0.94      0.83     11016
           1       0.45      0.12      0.19      4290

    accuracy                           0.71     15306
   macro avg       0.59      0.53      0.51     15306
weighted avg       0.65      0.71      0.65     15306



In [14]:
# Random Search
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

params = {"n_neighbors": range(1,5), "weights": ["uniform", "distance"]}
rsearch = RandomizedSearchCV(estimator=knn, param_distributions=params,cv=4,n_iter=8, random_state=5)
rsearch.fit(X_train, y_train)
rsearch_y_pred = rsearch.predict(X_test)

print(rsearch.best_score_)

0.7045786121366553


In [15]:
print(confusion_matrix(y_test2, rsearch_y_pred))
print(classification_report(y_test2, rsearch_y_pred))

[[9757 1259]
 [3752  538]]
              precision    recall  f1-score   support

           0       0.72      0.89      0.80     11016
           1       0.30      0.13      0.18      4290

    accuracy                           0.67     15306
   macro avg       0.51      0.51      0.49     15306
weighted avg       0.60      0.67      0.62     15306

